name: validate

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
        - uses: "actions/checkout@v3"
        - uses: home-assistant/actions/hassfest@master

  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
            category: "integration"
