name: Release component

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: compress files
        run: |
          cd custom_components
          tar -czvf senertec-${{ env.RELEASE_VERSION }}.tar.gz senertec
      - name: Release files
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            custom_components/senertec-${{ env.RELEASE_VERSION }}.tar.gz
